config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'accounts/customize'
  get 'accounts/table'
  get 'user/loading_card'
  get 'errors/not_found'
  get 'errors/internal_server_error'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_scope :user do
    get 'users/preferences' => 'registrations#preferences', as: :preferences
    put 'filter_youtube', to: 'registrations#filter_youtube'
  end

  root 'user#feed'
  get 'user/loading' => 'user#loading', as: :loading
  get 'user/:id' => 'user#show', as: :profile
  get 'user/:id/recommendations' => 'home#index', as: :recommendations
  get 'friends' => 'user#friends', as: :friends
  get 'match/:id' => 'user#match', as: :match
  get 'difference/:id' => 'user#difference', as: :difference

  resources :social_page, only: [ :index, :show ]

  # Rails expects the error pages to be served from /<error code>.
  # Adding these simple routes in config/routes.rb connects those
  # requests to the appropriate actions of the errors controller.
  # Using match ... :via => :all allows the error pages to be displayed
  #  for any type of request (GET, POST, PUT, etc.).
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  scope '/api' do
    scope '/v1' do
      scope '/social_pages' do
        get '/' => 'api_social_pages#index'
        scope '/default_feed' do
          get '/' => 'api_social_pages#default'
        end
        scope '/search' do
          get '/' => 'api_social_pages#search'
        end
        scope '/:id' do
          get '/' => 'api_social_pages#show'
          scope '/suggestions' do
            get '/' => 'api_social_pages#suggestions'
          end
        end
      end
      scope '/users' do
        scope '/:id' do
          get '/' => 'api_users#show'
          scope '/friends' do
            get '/' => 'api_users#friends'
          end
          scope '/social_pages_list' do
            get '/' => 'api_users#social_pages_list'
          end
          scope '/recommendations' do
            get '/' => 'api_users#recommendations'
          end
        end
      end
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  require_relative '../workers/load_content_feed_worker'
  require_relative './update_recent_posts'
  require_relative './find_recent_posts'

  before_action :authenticate_user!, :except => [:show, :feed]
  before_action :check_unauthorized, :except => [:show, :feed]

  def loading
    @filtered = []
    if current_user
      check_unauthorized
      if current_user.deviantart_filter
        @filtered << "DeviantArt"
      end
      if current_user.facebook_filter
        @filtered << "Facebook"
      end
      if current_user.instagram_filter
        @filtered << "Instagram"
      end
      if current_user.pinterest_filter
        @filtered << "Pinterest"
      end
      if current_user.reddit_filter
        @filtered << "Reddit"
      end
      if current_user.spotify_filter
        @filtered << "Spotify"
      end
      if current_user.tumblr_filter
        @filtered << "Tumblr"
      end
      if current_user.twitch_filter
        @filtered << "Twitch"
      end
      if current_user.twitter_filter
        @filtered << "Twitter"
      end
      if current_user.youtube_filter
        @filtered << "YouTube"
      end
    end
    LoadContentFeedWorker.perform_async(@filtered, current_user.id)
    redirect_to root_path
  end

  def show
    @user_show = true
    @user = User.find(params[:id])
    @social_pages = Kaminari.paginate_array(@user.social_pages_list.order(:page_name)).page(params[:page]).per(20)
    @filter = true
    @badges = 0

    if @user.deviantart_uid
      @badges = @badges + 1
    end
    if @user.facebook_uid
      @badges = @badges + 1
    end
    if @user.instagram_uid
      @badges = @badges + 1
    end
    if @user.pinterest_uid
      @badges = @badges + 1
    end
    if @user.reddit_uid
      @badges = @badges + 1
    end
    if @user.spotify_uid
      @badges = @badges + 1
    end
    if @user.tumblr_uid
      @badges = @badges + 1
    end
    if @user.twitch_uid
      @badges = @badges + 1
    end
    if @user.twitter_uid
      @badges = @badges + 1
    end
    if @user.google_uid
      @badges = @badges + 1
    end
    if @user.social_pages_list.count >= 50
      @badges = @badges + 1
    end
    if @user.social_pages_list.count >= 100
      @badges = @badges + 1
    end
    if @user.social_pages_list.count >= 250
      @badges = @badges + 1
    end
    if @user.social_pages_list.count >= 1000
      @badges = @badges + 1
    end
    if @user.following.all.count >= 10
      @badges = @badges + 1
    end
    if @user.following.all.count >= 50
      @badges = @badges + 1
    end
    if @user.following.all.count >= 100
      @badges = @badges + 1
    end
    if @user.id <= (User.all.count * 0.05).floor
      @badges = @badges + 1
    end

    @deviantart_count = 0
    @facebook_count = 0
    @instagram_count = 0
    @pinterest_count = 0
    @reddit_count = 0
    @spotify_count = 0
    @tumblr_count = 0
    @twitch_count = 0
    @twitter_count = 0
    @youtube_count = 0

    @user.find_liked_items.each do |p|
      begin
        case p.platform_name
        when "DeviantArt"
          @deviantart_count = @deviantart_count + 1
        when "Facebook"
          @facebook_count = @facebook_count + 1
        when "Instagram"
          @instagram_count = @instagram_count + 1
        when "Pinterest"
          @pinterest_count = @pinterest_count + 1
        when "Reddit"
          @reddit_count = @reddit_count + 1
        when "Spotify"
          @spotify_count = @spotify_count + 1
        when "Tumblr"
          @tumblr_count = @tumblr_count + 1
        when "Twitch"
          @twitch_count = @twitch_count + 1
        when "Twitter"
          @twitter_count = @twitter_count + 1
        when "YouTube"
          @youtube_count = @youtube_count + 1
        end
      rescue NoMethodError => e
        puts e
        next
      end
    end

    respond_to do |format|
      format.html do
        if request.xhr?
          render(:partial => 'social_pages', :object => @social_pages)
        end

      end
      format.js

      format.png do
        expires_in 24.hours, public: true
        kit = IMGKit.new render_to_string, width: 550, height: 850, "disable-smart-width": true
        send_data kit.to_png, type: "image/png", disposition: "inline"
      end
    end

    if current_user
      @user = User.find(params[:id])
      @user_pages = @user.social_pages_list.where.not(platform_name: @filtered)

      @my_pages = current_user.social_pages_list

      @matches = []
      @differences = []
      @matched = false

      @user_pages.each do |page|
        @my_pages.each do |mine|
          if page == mine
            @matches << mine
            @matched = true
          end
        end
        if !@matched
          @differences << page
        else
          @matched = false
        end
      end

      @matches_count = @matches.count
      @differences_count = @differences.count
    end
  end

  def feed

    if !current_user
      redirect_to home_index_url
    else
      @filtered = []
      if current_user
        check_unauthorized
        if current_user.deviantart_filter
          @filtered << "DeviantArt"
        end
        if current_user.facebook_filter
          @filtered << "Facebook"
        end
        if current_user.instagram_filter
          @filtered << "Instagram"
        end
        if current_user.pinterest_filter
          @filtered << "Pinterest"
        end
        if current_user.reddit_filter
          @filtered << "Reddit"
        end
        if current_user.spotify_filter
          @filtered << "Spotify"
        end
        if current_user.tumblr_filter
          @filtered << "Tumblr"
        end
        if current_user.twitch_filter
          @filtered << "Twitch"
        end
        if current_user.twitter_filter
          @filtered << "Twitter"
        end
        if current_user.youtube_filter
          @filtered << "YouTube"
        end
      end

      if current_user.last_recent_posts_sync < 1.hour.ago
        LoadContentFeedWorker.perform_async(@filtered, current_user.id)
      end

      @all_in_one_feed = true
      @user = current_user
      @filter = true
      if @filtered.include? "Pinterest"
        @social_pages = Kaminari.paginate_array(@user.social_pages_list.where.not(platform_name: @filtered, recent_post_date: [nil]).order(recent_post_date: :desc)).page(params[:page]).per(10)
      else
        # This query excludes Pinterest "users" and only shows "boards" because of
        # Pinterest's API restrictions
        @filtered << "Pinterest"
        @social_pages = Kaminari.paginate_array(@user.social_pages_list.where.not(board_creator: [nil]).or(@user.social_pages_list.where.not(platform_name: @filtered, recent_post_date: [nil])).order(recent_post_date: :desc)).page(params[:page]).per(10)
      end

      respond_to do |format|
        format.html do
          if request.xhr?
            render(:partial => 'social_pages', :object => @social_pages)
          end

        end
        format.js { render 'user/loading_card' }
      end
    end
  end

  def friends
    @social_pages = current_user.following.all
  end

  def match
    @filtered = []
    if current_user
      if current_user.deviantart_filter
        @filtered << "DeviantArt"
      end
      if current_user.facebook_filter
        @filtered << "Facebook"
      end
      if current_user.instagram_filter
        @filtered << "Instagram"
      end
      if current_user.pinterest_filter
        @filtered << "Pinterest"
      end
      if current_user.reddit_filter
        @filtered << "Reddit"
      end
      if current_user.spotify_filter
        @filtered << "Spotify"
      end
      if current_user.tumblr_filter
        @filtered << "Tumblr"
      end
      if current_user.twitch_filter
        @filtered << "Twitch"
      end
      if current_user.twitter_filter
        @filtered << "Twitter"
      end
      if current_user.youtube_filter
        @filtered << "YouTube"
      end
    end
    @filter = true
    @match = true
    @user = User.find(params[:id])
    @user_pages = @user.social_pages_list.where.not(platform_name: @filtered)

    @my_pages = current_user.social_pages_list

    @matches = []
    @differences = []
    @matched = false

    @user_pages.each do |page|
      @my_pages.each do |mine|
        if page == mine
          @matches << mine
          @matched = true
        end
      end
      if !@matched
        @differences << page
      else
        @matched = false
      end
    end

    @matches.sort! { |a,b| a.page_name.downcase <=> b.page_name.downcase }
    @social_pages = Kaminari.paginate_array(@matches).page(params[:page]).per(20)

    respond_to do |format|
      format.html do
        if request.xhr?
          render(:partial => 'social_pages', :object => @social_pages)
        end

      end
      format.js
    end
  end

  def difference
    @filtered = []
    if current_user
      if current_user.deviantart_filter
        @filtered << "DeviantArt"
      end
      if current_user.facebook_filter
        @filtered << "Facebook"
      end
        puts "Facebook is filtered"
      if current_user.instagram_filter
        @filtered << "Instagram"
      end
      if current_user.pinterest_filter
        @filtered << "Pinterest"
      end
      if current_user.reddit_filter
        @filtered << "Reddit"
      end
      if current_user.spotify_filter
        @filtered << "Spotify"
      end
      if current_user.tumblr_filter
        @filtered << "Tumblr"
      end
      if current_user.twitch_filter
        @filtered << "Twitch"
      end
      if current_user.twitter_filter
        @filtered << "Twitter"
      end
      if current_user.youtube_filter
        @filtered << "YouTube"
      end
    end
    @difference = true
    @filter = true
    @user = User.find(params[:id])
    @user_pages = @user.social_pages_list.where.not(platform_name: @filtered)

    @my_pages = current_user.social_pages_list

    @matches = []

app/controllers/users/deviantart_likes.rb
class Users::OmniauthCallbacksController::DeviantartLikes < Devise::OmniauthCallbacksController
  require_relative '../../workers/social_page_save_worker'
  require_relative '../../workers/make_recommendations_worker'

  def initialize(user)
    @user = User.find(user)
  end

  def add
    current_user = @user
    uri = URI.parse("https://www.deviantart.com/api/v1/oauth2/user/friends/" + current_user.deviantart_uid + "?access_token=" + current_user.deviantart_token + "&limit=50")
    response = Net::HTTP.get_response(uri)
    write = JSON.parse response.body.gsub('=>', ':')
    puts write["error"]
    if write["error"]
      flash[:notice] = "DeviantArt says you're syncing your account too much! Try syncing later."
      redirect_to :controller => :accounts, :action => :customize and return
    end

    deviants = write["results"] || []
    ids = []

    deviants.each do |dev|
      ids << dev["user"]["username"]
    end
    while write["has_more"] do
      uri = URI.parse("https://www.deviantart.com/api/v1/oauth2/user/friends/" + current_user.deviantart_uid + "?access_token=" + current_user.deviantart_token + "&limit=50&offset=" + write["next_offset"].to_s)
      response = Net::HTTP.get_response(uri)
      write_more = JSON.parse response.body.gsub('=>', ':')
      if write["error"]
        flash[:notice] = "DeviantArt says you're syncing your account too much! Try syncing later."
        redirect_to :controller => :accounts, :action => :customize and return
      end
      deviants = write_more["results"]

      deviants.each do |dev|
        ids << dev["user"]["username"]
      end
      write = write_more
    end
    deviantart_users = []
    deviantart_lowres = []

    ids.each do |id|
      uri = URI.parse("https://www.deviantart.com/api/v1/oauth2/user/profile/" + id + "?access_token=" + current_user.deviantart_token)
      response = Net::HTTP.get_response(uri)
      write = JSON.parse response.body.gsub('=>', ':')
      if write["profile_pic"]
        deviantart_users << write
      else
        deviantart_lowres << write
      end
    end

    @new_pages = []
    @friends = []

    deviantart_lowres.each do |profile|
      profile["user"]["usericon"] = profile["user"]["usericon"].sub! 'http://', 'https://'
      @friends << profile["user"]["username"]
      @new_pages << {
        :page_name => profile["user"]["username"],
        :follow_count => profile["stats"]["profile_pageviews"].to_s,
        :description => profile["bio"],
        # :page_image_url => profile["profile_pic"]["content"]["src"],
        :page_image_url => profile["user"]["usericon"],
        :platform_id => profile["user"]["userid"],
        :platform_url => profile["profile_url"],
        :platform_name => "DeviantArt",
        :content_count => profile["stats"]["user_deviations"],
        :website => profile["website"],
        :banner_image_url => profile["cover_photo"],
        :location => profile["country"]
      }
    end

    deviantart_users.each do |profile|
      profile["user"]["usericon"] = profile["user"]["usericon"].sub! 'http://', 'https://'
      @friends << profile["user"]["username"]
      @new_pages << {
        :page_name => profile["user"]["username"],
        :follow_count => profile["stats"]["profile_pageviews"].to_s,
        :description => profile["bio"],
        :page_image_url => profile["profile_pic"]["content"]["src"],
        # :page_image_url => profile["user"]["usericon"],
        :platform_id => profile["user"]["userid"],
        :platform_url => profile["profile_url"],
        :platform_name => "DeviantArt",
        :content_count => profile["stats"]["user_deviations"],
        :website => profile["website"],
        :banner_image_url => profile["cover_photo"],
        :location => profile["country"]
      }
    end

    @friends.each do |friend|
      user = User.find_by(deviantart_uid: friend)
      if user
        if !current_user.following.where(deviantart_uid: user.deviantart_uid).first
          current_user.following << user
        end
        if user.social_pages_list.where(platform_id: current_user.deviantart_uid)
          if !user.following.where(deviantart_uid: current_user.deviantart_uid).first
            user.following << current_user
          end
        end
      end
    end

    SocialPageSaveWorker.perform_async(@new_pages, current_user.id)

    current_user.save
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_loading_card.html.erb
    <div class="social-origin-stridr"></div>
    <div class="row">
      <div class="col-xs-8 card-head-title">
        <h3>
          <span id="loading_message"><%= current_user.feed_status %></span>
          <span class="fa fa-circle-o-notch loading" aria-hidden="true"></span>
        </h3>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 card-bar">
        <span>
          Your chronological content feed is loading
        </span>
        <hr>
      </div>
    </div>

app/views/user/_social_pages.html.erb
<% @social_pages.each do |page| %>
  <%= render partial: "layouts/social_page", locals: { page: page, current_user: current_user } %>
<% end %>

app/views/user/difference.html.erb
<!-- Main body content. Cards go here. -->
<div id="card-wrapper">
  <!-- BEGIN USER PROFILE -->
<div class="card-container card-container-stridr">
    <div class="social-origin-stridr"></div>
    <div class="row">
      <div class="col-xs-8 card-head-title">
        <h3>
          <%= @user.username %>'s unmatched interests
        </h3>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 card-bar">
        <span>
          Stridr
        </span>
        <hr>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-5  card-head-logo card-head-logo-stridr" style="background-image: url(<%= @user.image %>)"></div>
      <div class="col-xs-7 col-sm-9 card-body">
        <!-- strip_tags removes potential markup from Tumblr profile descriptions -->
        <p>Here's a list of <%= @user.username %>'s followed social pages that you don't follow. Don't forget to add all of your social <%= link_to('Accounts', accounts_customize_path)  %> to increase accuracy!</p>
        <ul>
          <li>
            <%= link_to match_path(@user.id) do %>
              <%= @matches.count %> interests in common
            <% end %>
          </li>
          <li>
            <%= @differences.count %> interests you don't share
          </li>
        </ul>

      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 card-based-on">
        <span>
          Scroll on!
        </span>
      </div>
    </div>
  </div>
  <!-- END USER PROFILE -->

  <!-- BEGIN SOCIAL_PAGES.EACH -->
<% if @differences.count == 0 %>
<h2>...oh. There's nothing to show!</h2>
  <% if @user.id == current_user.id %>
  <h3>Stalking your own profile, eh?</h3>
  <% else %>
  <h3>Connect your social <%= link_to('Accounts', accounts_customize_path)  %> to increase accuracy! <br /><br />Alternatively, you may have too many filters on. <%= link_to "Whitelist more platforms to see more.", edit_user_registration_path %></h3>
  <% end %>
<% end %>
<%= render partial: 'social_pages', object: @social_pages, locals: { current_user: current_user } %>
  <!-- END SOCIAL_PAGES.EACH -->
</div> <!-- end card-wrapper -->
<% if !@social_pages.last_page? %>
<div class="card-container card-container-stridr text-center footer">
  <div class="row">
    <div class="col-xs-12 card-head-title">
      <h3 class="pagination">
        <%= link_to_next_page(@social_pages, "Load More", remote: true) %>
      </h3>
      <span class="fa fa-circle-o-notch loading" aria-hidden="true"></span>
    </div>
  </div>
</div>
<% end %>

app/views/user/feed.html.erb
<div id="loading_card" class="card-container card-container-stridr">
  <%= render partial: 'user/loading_card', locals: { current_user: current_user } %>
</div>
<!-- Main body content. Cards go here. -->
<div id="card-wrapper">
<!-- BEGIN SOCIAL_PAGES.EACH -->
<% if @social_pages.count == 0 %>
<h2>...oh. There's nothing to show!</h2>
<h3>Connect your social <%= link_to('Accounts', accounts_customize_path)  %> to populate your feed!</h3>
<% end %>
<%= render partial: 'social_pages', object: @social_pages, locals: { current_user: current_user } %>
  <!-- END SOCIAL_PAGES.EACH -->
</div> <!-- end card-wrapper -->

<% if !@social_pages.last_page? %>
<div class="card-container card-container-stridr text-center footer">
  <div class="row">
    <div class="col-xs-12 card-head-title">
      <h3 class="pagination">
        <%= link_to_next_page(@social_pages, "Load More", remote: true) %>
      </h3>
      <span class="fa fa-circle-o-notch loading" aria-hidden="true"></span>
    </div>
  </div>
</div>
<% end %>

app/views/user/friends.html.erb
<!-- Main body content. Cards go here. -->
<div id="card-wrapper">
  <% if current_user.following.count < 1 %>
  <!-- BEGIN NOTIFICATION -->
  <div class="card-container card-container-stridr">
    <div class="social-origin-stridr"></div>
    <div class="row">
      <div class="col-xs-8 card-head-title">
        <h3>
          ...oh, no! You have no friends!
        </h3>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 card-bar">
        <span>
          Stridr
        </span>
        <hr>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-5  card-head-logo card-head-logo-stridr" style="background-image: url(<%= current_user.image %>)"></div>
      <div class="col-xs-7 col-sm-9 card-body">
        <p>Invite your friends to Stridr so you can compare interests and increase Stridr's suggestion accuracy!</p>
        <ul>
          <li>
            Compare <%= current_user.find_liked_items.count %> of your likes/follows with your friends!
          </li>
          <li>
            Share your profile:
          </li>
          <li>
            <%= social_share_button_tag("Compare your likes/follows/subscriptions on Social Media with mine!", :url => "https://stridr.social/user/" + current_user.id.to_s) %>
          </li>
        </ul>

      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 card-based-on">
        <span>
          What're you waiting for?!
        </span>
      </div>
    </div>
  </div>
  <!-- END NOTIFICATION -->
  <% end %>

<% @social_pages.each do |page| %>
<!-- BEGIN USER PROFILES -->
<%= link_to profile_path(page.id) do %>
<div class="card-container card-container-stridr">
    <div class="social-origin-stridr"></div>
    <div class="row">
      <div class="col-xs-8 card-head-title">
        <h3>
          <%= page.username %>
        </h3>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 card-bar">
        <span>
          <% if !page.location %>
          Stridr
          <% else %>
          <%= page.location %>
          <% end %>
        </span>
        <hr>
      </div>
    </div>
    <div class="row">
      <% if page.image %>
      <div class="col-xs-5  card-head-logo card-head-logo-stridr" style="background-image: url(<%= page.image %>)"></div>
      <% else %>
      <div class="col-xs-5  card-head-logo card-head-logo-stridr" style="background-image:url(<%= asset_path 'logo-bw.png' %>;)"></div>
      <% end %>
      <div class="col-xs-7 col-sm-9 card-body">
        <p>
          <% if !page.description %>
          A Stridr user.
          <% else %>
          <%= page.description %>
          <% end %>
        </p>
        <ul>
          <li>
            <%= page.find_liked_items.count %> likes/follows across social media
          </li>
        </ul>

      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 card-based-on">
        <span>
          Scroll on!
        </span>
      </div>
    </div>
  </div>
  <% end %>
  <!-- END USER PROFILE -->
<% end %>

<% if current_user.following.count > 0 %>
<!-- BEGIN CLOSING NOTIFICATION -->
<div class="card-container card-container-stridr">
  <div class="social-origin-stridr"></div>
  <div class="row">
    <div class="col-xs-8 card-head-title">
      <h3>
        Want to see more?
      </h3>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 card-bar">
      <span>
        Stridr
      </span>
      <hr>
    </div>
  </div>
  <div class="row">
      <% if current_user.image %>
      <div class="col-xs-5  card-head-logo card-head-logo-stridr" style="background-image: url(<%= current_user.image %>)"></div>
      <% else %>
      <div class="col-xs-5  card-head-logo card-head-logo-stridr" style="background-image:url(<%= asset_path 'logo-bw.png' %>;)"></div>
      <% end %>
      <div class="col-xs-7 col-sm-9 card-body">
      <p>Invite your friends to Stridr so you can compare interests and increase Stridr's suggestion accuracy!</p>
      <ul>
        <li>
          Compare <%= current_user.find_liked_items.count %> of your likes/follows with your friends!
        </li>
        <li>
          Share your profile:
        </li>
        <li>
          <%= social_share_button_tag("Compare your likes/follows/subscriptions on Social Media with mine!", :url => "https://stridr.social/user/" + current_user.id.to_s) %>
        </li>
      </ul>

    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 card-based-on">
      <span>
        What're you waiting for?!
      </span>
    </div>
  </div>
</div>
<!-- END CLOSING NOTIFICATION -->
<% end %>
</div> <!-- end card-wrapper -->

app/views/user/loading.html.erb
<!-- Main body content. Cards go here. -->
<div id="card-wrapper">
<div id="loading_card" class="card-container card-container-stridr" style="margin-top:40vh;">
  <%= render partial: 'user/loading_card', locals: { current_user: current_user } %>
</div>

</div> <!-- end card-wrapper -->

app/views/user/loading_card.js.erb
var element = $("#loading_card");
element.html("<%= j(render(partial: 'user/loading_card', locals: { current_user: current_user })) %>");

app/views/user/match.html.erb
<!-- Main body content. Cards go here. -->
<div id="card-wrapper">
  <!-- BEGIN USER PROFILE -->
<div class="card-container card-container-stridr">
    <div class="social-origin-stridr"></div>
    <div class="row">
      <div class="col-xs-8 card-head-title">
        <h3>
          Your matches with <%= @user.username %>
        </h3>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 card-bar">
        <span>
          Stridr
        </span>
        <hr>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-5  card-head-logo card-head-logo-stridr" style="background-image: url(<%= @user.image %>)"></div>
      <div class="col-xs-7 col-sm-9 card-body">
        <!-- strip_tags removes potential markup from Tumblr profile descriptions -->
        <p>Here's a list of matches with <%= @user.username %>. Don't forget to add all of your social <%= link_to('Accounts', accounts_customize_path)  %> to increase accuracy!</p>
        <ul>
          <li>
            <%= @matches.count %> interests in common
          </li>
          <li>
            <%= link_to difference_path(@user.id) do %>
              <%= @differences.count %> interests you don't share
            <% end %>
          </li>
        </ul>

      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 card-based-on">
        <span>
          Scroll on!
        </span>
      </div>
    </div>
  </div>
  <!-- END USER PROFILE -->

  <!-- BEGIN SOCIAL_PAGES.EACH -->
<% if @matches.count == 0 %>
<h2>...oh. There's nothing to show!</h2>
  <% if @user.id == current_user.id %>
  <h3>Stalking your own profile, eh?</h3>
  <% else %>
  <h3>Connect your social <%= link_to('Accounts', accounts_customize_path)  %> to increase accuracy! <br /><br />Alternatively, you may have too many filters on. <%= link_to "Whitelist more platforms to see more.", edit_user_registration_path %></h3>
  <% end %>
<% end %>
<%= render partial: 'social_pages', object: @social_pages, locals: { current_user: current_user } %>
  <!-- END SOCIAL_PAGES.EACH -->
</div> <!-- end card-wrapper -->
<% if !@social_pages.last_page? %>
<div class="card-container card-container-stridr text-center footer">
  <div class="row">
    <div class="col-xs-12 card-head-title">
      <h3 class="pagination">
        <%= link_to_next_page(@social_pages, "Load More", remote: true) %>
      </h3>
      <span class="fa fa-circle-o-notch loading" aria-hidden="true"></span>
    </div>
  </div>
</div>
<% end %>