config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'accounts/customize'
  get 'accounts/table'
  get 'user/loading_card'
  get 'errors/not_found'
  get 'errors/internal_server_error'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_scope :user do
    get 'users/preferences' => 'registrations#preferences', as: :preferences
    put 'filter_youtube', to: 'registrations#filter_youtube'
  end

  root 'user#feed'
  get 'user/loading' => 'user#loading', as: :loading
  get 'user/:id' => 'user#show', as: :profile
  get 'user/:id/recommendations' => 'home#index', as: :recommendations
  get 'friends' => 'user#friends', as: :friends
  get 'match/:id' => 'user#match', as: :match
  get 'difference/:id' => 'user#difference', as: :difference

  resources :social_page, only: [ :index, :show ]

  # Rails expects the error pages to be served from /<error code>.
  # Adding these simple routes in config/routes.rb connects those
  # requests to the appropriate actions of the errors controller.
  # Using match ... :via => :all allows the error pages to be displayed
  #  for any type of request (GET, POST, PUT, etc.).
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  scope '/api' do
    scope '/v1' do
      scope '/social_pages' do
        get '/' => 'api_social_pages#index'
        scope '/default_feed' do
          get '/' => 'api_social_pages#default'
        end
        scope '/search' do
          get '/' => 'api_social_pages#search'
        end
        scope '/:id' do
          get '/' => 'api_social_pages#show'
          scope '/suggestions' do
            get '/' => 'api_social_pages#suggestions'
          end
        end
      end
      scope '/users' do
        scope '/:id' do
          get '/' => 'api_users#show'
          scope '/friends' do
            get '/' => 'api_users#friends'
          end
          scope '/social_pages_list' do
            get '/' => 'api_users#social_pages_list'
          end
          scope '/recommendations' do
            get '/' => 'api_users#recommendations'
          end
        end
      end
    end
  end

end

app/views/layouts/_card_reason.html.erb
  <span>
    <% if @user_show %>
    Liked/followed/subscribed by <%= @user.username %>
    <% end %>
    <% if @match %>
    Liked/followed/subscribed by you and <%= @user.username %>
    <% end %>
    <% if @difference %>
    Liked/followed/subscribed by <%= @user.username %>
    <% end %>
    <% if @search %>
    Search Result
    <% elsif @home %>
    Suggested by Stridr
    <% end %>
    <% if @social_page_show %>
    Suggested by Stridr
    <% end %>
  </span>

app/views/layouts/_navbar.html.erb
<!-- Slide out navigation. Only visible on smaller screens -->
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="toggleNav(false)">&times;</a>
  <% if current_user %>
  <p>
    Welcome back, <%= current_user.username %>
  </p>
  <% end %>
  <%= render partial: 'layouts/search' %>
  <%= link_to 'Home', root_path %>
  <% if user_signed_in? %>
    <%= link_to('Reload Content Feed', loading_path) %>
    <%= link_to('Sync Social Accounts', accounts_customize_path)  %>
    <%= link_to('My Profile', profile_path(current_user.id)) %>
    <%= link_to('Recommendations', recommendations_path(current_user.id)) %>
    <%= link_to('Friends', friends_path) %>
    <%= link_to('Settings', edit_user_registration_path)  %>
  <% end %>
  <br />
  <% if user_signed_in? %>
    <%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %>
  <% else %>
    <%= link_to('Sign In', new_user_session_path)  %>
  <% end %>
  <a href="https://goo.gl/forms/UiiZqY6PFbfwVXjJ3">Feedback</a>
</div>

<!-- Main top bar. Serves as navigation on desktop size screens -->
<div class="navigation-wrapper">
  <nav class="navbar-fixed-top">
    <ul class="logged-in-desktop-links">
      <li>
        <a href="https://goo.gl/forms/UiiZqY6PFbfwVXjJ3">Feedback</a>
      </li>
      <% if user_signed_in? %>
        <li>
          <a href="#" rel="account_popover" data-placement="bottom" data-popover-content="#accountPopover"><span class="glyphicon glyphicon-user"></span></a>
        </li>
        <div id="accountPopover" class="hide">
          <h5>Account</h5>
          <ul>
            <li>
              <%= link_to('Reload Content Feed', loading_path) %>
            </li>
            <li>
              <%= link_to('Sync Social Accounts', accounts_customize_path) %>
            </li>
            <li>
              <%= link_to('My Profile', profile_path(current_user.id)) %>
            </li>
            <li>
              <%= link_to('Recommendations', recommendations_path(current_user.id)) %>
            </li>
            <li>
              <%= link_to('Friends', friends_path) %>
            </li>
          </ul>
        </div>

        <li>
          <a href="#" rel="settings_popover" data-placement="bottom" data-popover-content="#settingsPopover"><span class="glyphicon glyphicon-cog"></span></a>
        </li>
        <div id="settingsPopover" class="hide">
          <ul>
            <li>
              <%= link_to('Settings', edit_user_registration_path)  %>
            </li>
            <li>
              <%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %>
            </li>
          </ul>
        </div>
        <li>
          <%= link_to content_tag(:span, "", class: "glyphicon glyphicon-home"), root_path %>
        </li>

      <% else %>
      <li>
        <%= link_to('Log In', new_user_session_path)  %>
      </li>
      <% end %>
      <% if current_user %>
      <li>
        <p>
          Welcome back, <%= current_user.username %>
        </p>
      </li>
      <% end %>
    </ul>
    <%= link_to image_tag("logo.png", alt: "STRIDR Logo with disclaimer: Under active development"), root_path %>
    <div class="col-xs-3 search-bar logged-in-desktop-links">
      <%= render partial: 'layouts/search' %>
    </div>
    <button id="mobile-nav-icon" onclick="toggleNav(true)" type="button" class="btn btn-default btn-md">
      <span class="glyphicon glyphicon-menu-hamburger"></span>
    </button>
    <% if flash.present? %>
    <div class="flash">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert alert-info" do %>
          <div>
            <%= msg.html_safe %>
            <i class="fa fa-times" aria-hidden="true"></i>
          </div>
        <% end %>
      <% end %>
    </div>
    <% end %>
  </nav>
</div>

app/views/layouts/_search.html.erb
<%= form_tag root_path, :class => 'navbar-form', :method => :get do %>
  <div class="input-group">
    <span class="input-group-btn">
      <button class="btn btn-default search-button" type="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
    </span>
    <%= text_field_tag :search, params[:search], :class => 'form-control results-search-txt', :placeholder=>"Search...", :id => nil %>
  </div><!-- /input-group -->
  <div class="results"></div>
<% end %>

app/views/layouts/_sharebuttons.html.erb
<% if @social_page_show && page == @social_page %>
<div style="margin-top: 8px;">
  <%= render partial: 'layouts/sharebuttons/facebook_share', locals: { page: page } %>
</div>
<div style="margin-top: 8px;">
  <%= render partial: 'layouts/sharebuttons/twitter_share', locals: { page: page } %>
</div>
<div style="margin-top: 3px;">
  <%= render partial: 'layouts/sharebuttons/tumblr_share', locals: { page: page } %>
</div>
<div style="margin-top: 6px;">
  <%= render partial: 'layouts/sharebuttons/pinterest_share', locals: { page: page } %>
</div>
<% end %>

app/views/layouts/_social_page.html.erb
<% if page.platform_name.downcase == "deviantart" %>
    <%= render partial: "layouts/cards/deviantart_card", locals: { page: page } %>
<% end %>
<% if page.platform_name.downcase == "facebook" %>
    <%= render partial: "layouts/cards/facebook_card", locals: { page: page } %>
<% end %>
<% if page.platform_name.downcase == "instagram" %>
    <%= render partial: "layouts/cards/instagram_card", locals: { page: page } %>
<% end %>
<% if page.platform_name.downcase == "pinterest" %>
    <%= render partial: "layouts/cards/pinterest_card", locals: { page: page } %>
<% end %>
<% if page.platform_name.downcase == "reddit" %>
    <%= render partial: "layouts/cards/reddit_card", locals: { page: page } %>
<% end %>
<% if page.platform_name.downcase == "spotify" %>
    <%= render partial: "layouts/cards/spotify_card", locals: { page: page } %>
<% end %>
<% if page.platform_name.downcase == "tumblr" %>
    <%= render partial: "layouts/cards/tumblr_card", locals: { page: page } %>
<% end %>
<% if page.platform_name.downcase == "twitter" %>
    <%= render partial: "layouts/cards/twitter_card", locals: { page: page } %>
<% end %>
<% if page.platform_name.downcase == "twitch" %>
    <%= render partial: "layouts/cards/twitch_card", locals: { page: page } %>
<% end %>
<% if page.platform_name.downcase == "youtube" %>
    <%= render partial: "layouts/cards/youtube_card", locals: { page: page } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">

    <%= render 'application/favicon' %>
    <meta name="keywords" content="stridr, all-in-one-social-media, social-discovery, social-media-aggregator, social-recommender, social-network-aggregator, find-new-content, social-content-discovery, content-discovery, north-island-college-class-project" />
    <% if @social_page_show %>
    <!-- OG tags -->
      <title>Stridr | Visit <%= @social_page.page_name %>, a social page on <%= @social_page.platform_name %></title>      <meta name="description" content="Check out <%= @social_page.page_name %>, a <%= @social_page.platform_name %> page discovered through https://www.stridr.social !">
      <meta property="og:site_name" content="Stridr"/>
      <meta property="og:title" content="Check out <%= @social_page.page_name %>!"/>
      <meta property="og:description" content="A <%= @social_page.platform_name %> page discovered through www.stridr.social">
      <meta property="og:image" content="<%= @social_page.avatar.url %>">
      <meta property="og:url" content="https://www.stridr.social<%= social_page_path(@social_page) %>">
      <meta property="og:type" content="website">
      <meta property="fb:app_id" content="<%= ENV['FACEBOOK_ID'] %>">
    <!-- Twitter tags -->
      <meta name="twitter:card" content="summary">
      <meta name="twitter:site" content="@stridrsocial">
      <meta name="twitter:title" content="Check out <%= @social_page.page_name %>!">
      <meta name="twitter:description" content="A <%= @social_page.platform_name %> page discovered through www.stridr.social">
      <meta name="twitter:image" content="<%= @social_page.avatar.url %>">
      <meta name="twitter:domain" content="https://www.stridr.social">
    <% elsif @user_show %>
      <title>Stridr | <%= @user.username %></title>
      <!-- OG -->
      <meta name="description" content="Compare your interests with <%= @user.username %> and find them on social media!" />
      <meta property="og:site_name" content="Stridr"/>
      <meta property="og:title" content="Compare your interests with <%= @user.username %> and find them on social media!"/>
      <meta property="og:description" content="An all-in-one social media app to discover great new content."/>
      <meta property="og:image" content="https://stridr.social/user/<%= @user.id.to_s %>.png">
      <meta property="og:url" content="https://stridr.social<%= profile_path(@user) %>">
      <meta property="og:type" content="website">
      <meta property="fb:app_id" content="<%= ENV['FACEBOOK_ID'] %>">
    <!-- Twitter tags -->
      <meta name="twitter:card" content="summary">
      <meta name="twitter:site" content="@stridrsocial">
      <meta name="twitter:title" content="<%= @user.username %> on Stridr">
      <meta name="twitter:description" content="Compare your interests with <%= @user.username %> and find them on social media!">
      <meta name="twitter:image" content="https://stridr.social/user/<%= @user.id.to_s %>.png">
      <meta name="twitter:domain" content="https://www.stridr.social">
    <% else %>
      <title>Stridr | Your All-in-One Social Discovery Engine</title>
      <meta name="description" content="Stridr looks at everything you like on social media and suggests more cool stuff; cross platform, all on Stridr.social!" />
      <meta property="og:site_name" content="Stridr"/>
      <meta property="og:title" content="Stridr looks at everything you like on social media and offers ways to discover cool new content!"/>
      <meta property="og:description" content="An all-in-one social media app to discover great new content."/>
      <meta property="og:image" content="https://stridr.social/og-image.jpg">
      <meta property="og:url" content="https://stridr.social/">
      <meta property="og:type" content="website">
      <meta property="fb:app_id" content="<%= ENV['FACEBOOK_ID'] %>">
    <% end %>
    <meta name="p:domain_verify" content="1eac0b386607447d8f8d9733dc97a7cc"/>
    <meta name="google-site-verification" content="6kI0MvERnzwgtvsCMZ0BG0mI-YhCtVmBm9RsEMriy1A" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "Organization",
        "name": "Stridr",
        "url": "https://www.stridr.social",
        "logo": "https://stridr.social/logo-final.png",
        "sameAs": [
            "https://www.facebook.com/stridrsocial",
            "https://www.pinterest.com/stridrsocial",
            "https://stridrsocial.tumblr.com/",
            "https://twitter.com/stridrsocial"
        ]
      },
      {
        "@context": "http://schema.org/name",
        "@type": "WebSite",
        "name": "Stridr",
        "alternateName": "stridr.social",
        "url": "https://stridr.social"
      }
    </script>

    <!-- Facebook share button JS -->
    <script>
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.9&appId=1641816879167434";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    </script>
    <!-- Twitter share button JS -->
    <script>
      window.twttr = (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0],
          t = window.twttr || {};
        if (d.getElementById(id)) return t;
        js = d.createElement(s);
        js.id = id;
        js.src = "https://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js, fjs);

        t._e = [];
        t.ready = function(f) {
          t._e.push(f);
        };

        return t;
      }(document, "script", "twitter-wjs"));
    </script>
    <!-- Tumblr share button JS -->
    <script>
      !function(d,s,id){var js,ajs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://assets.tumblr.com/share-button.js";ajs.parentNode.insertBefore(js,ajs);}}(document, "script", "tumblr-js");
    </script>
    <!-- Pinterest pinit button JS -->
    <script
        type="text/javascript"
        async defer
        src="//assets.pinterest.com/js/pinit.js"
    ></script>
  </head>

  <body id="<%= controller_name %>_<%= action_name %>">
  <div id="fb-root"></div>
    <%= render "layouts/navbar" %>
    <%= yield %>

    <div id="user-id" style="display:none;">
      <% if current_user %>
      <%= current_user.id %>
      <% end %>
    </div>
    <script>
      var USER_ID = document.getElementById("user-id").textContent;
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-99135446-1', 'auto');
      ga('send', 'pageview');
      ga('set', 'userId', USER_ID); // Set the user ID using signed-in user_id.
    </script>

  </body>
</html>